### PR TITLE
Proof for induction from base case

### PR DESCRIPTION
**Pull request by heftymouse**

### CODE REVIEW

**Comment by heftymouse** [comment]
I'll rebase once you look at this

**Review by nairadithya — CHANGES_REQUESTED** [review]
# REJECTED

Dear god no, we do not allow for conflict in this society.

Take that pdf out of my sight.

**Comment by heftymouse** [comment]
SIR YES SIR I WILL HAVE IT DONE YESTERDAY

**Review by nairadithya — APPROVED** [review]
This is the kind of work ethic we all need to learn from!

You're promoted!!

**Pull request merged**
